from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = PROJECT_ROOT / "templates"


def normalize_report_type(report_type: str) -> str:
    aliases = {
        "incident": "incident_report",
        "arrest": "arrest_report",
        "force": "use_of_force",
        "use-of-force": "use_of_force",
        "use_of_force_report": "use_of_force",
        "accident": "accident_report",
    }
    return aliases.get(report_type, report_type)


def load_template(report_type: str) -> dict[str, Any]:
    normalized = normalize_report_type(report_type)
    template_path = TEMPLATES_DIR / f"{normalized}.json"
    with template_path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def get_nested_value(data: dict[str, Any], dotted_path: str | None) -> Any:
    if not dotted_path:
        return None

    current: Any = data
    for part in dotted_path.split("."):
        if isinstance(current, dict):
            current = current.get(part)
        else:
            return None
    return current


def missing_value(value: Any) -> bool:
    return value is None or value == "" or value == [] or value == {}


def build_structured_report(
    report_type: str,
    transcript: str,
    extraction: dict[str, Any],
    corrections: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    template = load_template(report_type)
    fields: dict[str, Any] = {}

    for field in template.get("fields", []):
        value = get_nested_value(extraction, field.get("source"))
        fields[field["name"]] = (
            {"status": "not_available", "reason": "Not provided in officer account"}
            if missing_value(value)
            else value
        )

    return {
        "report_type": template["report_type"],
        "title": template["title"],
        "generated_at": datetime.now(UTC).isoformat(),
        "ai_disclosure": "Draft generated by AI from officer verbal account.",
        "fields": fields,
        "narrative": {
            "source": "conversation_transcript",
            "draft": transcript.strip(),
        },
        "applied_correction_examples": corrections or [],
    }

